create extension if not exists pgcrypto;
create table if not exists public.mv_brands(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,website text,category text,contact_name text,email text,instagram text,status text default 'prospect',created_at timestamptz not null default now());
create table if not exists public.mv_creators(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,email text,platform text,handle text,niche text,followers bigint,rate numeric(14,2),status text default 'prospect',created_at timestamptz not null default now());
create table if not exists public.mv_campaigns(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,brand_name text,objective text,deliverables text,deadline date,budget numeric(14,2),status text default 'planning',created_at timestamptz not null default now());
create table if not exists public.mv_deals(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,brand_name text,creator_name text,value_inr numeric(14,2) not null default 0,commission_percent numeric(5,2) not null default 20 check(commission_percent>=0 and commission_percent<=100),status text default 'prospect',due_date date,created_at timestamptz not null default now());
create table if not exists public.mv_followups(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,contact_email text,due_at date,notes text,status text default 'pending',created_at timestamptz not null default now());
create table if not exists public.mv_outreach(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,brand_name text not null,recipient_email text,subject text not null,body text not null,status text default 'draft',sent_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.mv_gmail_connections(user_id uuid primary key references auth.users(id) on delete cascade,email text,refresh_token_encrypted text,access_token_encrypted text,access_token_expires_at timestamptz,scopes text,updated_at timestamptz not null default now());
create index if not exists mv_brands_user_created_idx on public.mv_brands(user_id,created_at desc);create index if not exists mv_creators_user_created_idx on public.mv_creators(user_id,created_at desc);create index if not exists mv_outreach_user_created_idx on public.mv_outreach(user_id,created_at desc);create index if not exists mv_deals_user_created_idx on public.mv_deals(user_id,created_at desc);
alter table public.mv_brands enable row level security;alter table public.mv_creators enable row level security;alter table public.mv_campaigns enable row level security;alter table public.mv_deals enable row level security;alter table public.mv_followups enable row level security;alter table public.mv_outreach enable row level security;alter table public.mv_gmail_connections enable row level security;
do $$ declare t text;begin foreach t in array array['mv_brands','mv_creators','mv_campaigns','mv_deals','mv_followups','mv_outreach'] loop execute format('drop policy if exists "Users manage own %s" on public.%I',t,t);execute format('create policy "Users manage own %s" on public.%I for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid())',t,t);end loop;end $$;
-- Intentionally no browser RLS policy for mv_gmail_connections. Only server routes using the service-role key can read/write encrypted tokens.